// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWuvPmxNDi-X1vZg79Hcxe8-WVkfGOSBg',
    appId: '1:192828381049:web:a7aee2b7006d016b8c41a8',
    messagingSenderId: '192828381049',
    projectId: 'bloc-socialmediaapp',
    authDomain: 'bloc-socialmediaapp.firebaseapp.com',
    storageBucket: 'bloc-socialmediaapp.firebasestorage.app',
    measurementId: 'G-V04M5ZDP2S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmt3qrHpDLj5hznM_YeEzygBZSsr9y3Tc',
    appId: '1:192828381049:android:4a53441d0e4f9ec98c41a8',
    messagingSenderId: '192828381049',
    projectId: 'bloc-socialmediaapp',
    storageBucket: 'bloc-socialmediaapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF9Fuf72LqIKyCotSYzmkUIFiwCioPED8',
    appId: '1:192828381049:ios:88d05f1f5b12204e8c41a8',
    messagingSenderId: '192828381049',
    projectId: 'bloc-socialmediaapp',
    storageBucket: 'bloc-socialmediaapp.firebasestorage.app',
    iosBundleId: 'com.example.todoBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF9Fuf72LqIKyCotSYzmkUIFiwCioPED8',
    appId: '1:192828381049:ios:88d05f1f5b12204e8c41a8',
    messagingSenderId: '192828381049',
    projectId: 'bloc-socialmediaapp',
    storageBucket: 'bloc-socialmediaapp.firebasestorage.app',
    iosBundleId: 'com.example.todoBloc',
  );
}
